name: videoflow 
description: "video flow"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  yaml: ^3.1.2
  intl: ^0.19.0
  http: ^1.4.0
  html: ^0.15.4
  url_launcher: ^6.3.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  path: ^1.9.1
  puppeteer: ^3.18.0
  provider: ^6.1.2
  uuid: ^4.4.0
  file_picker: ^8.0.6
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dev: ^1.0.0
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ffmpeg/ffmpeg.exe
    - assets/ffmpeg/ffplay.exe
    - assets/app_config.yaml
    - assets/chrome-win/
    - assets/chrome-win/locales/
    - assets/chrome-win/MEIPreload/
    - assets/chrome-win/PrivacySandboxAttestationsPreloaded/
    - assets/chrome-win/IwaKeyDistribution/
