name: videoflow 
description: "videoflow"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1  # dart
  flutter: ">=3.35.0" # flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  yaml: ^3.1.2
  intl: ^0.20.2
  http: ^1.4.0
  html: ^0.15.4
  url_launcher: ^6.3.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  path: ^1.9.1
  provider: ^6.1.2
  uuid: ^4.4.0
  file_picker: ^8.0.6
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dev: ^1.0.0
  package_info_plus: ^8.3.1

   #Widget
  flutter_staggered_grid_view: ^0.7.0 #瀑布流/GridView
  flutter_easyrefresh: 2.2.2 #下拉刷新、上拉加载
  extended_image: ^9.1.0 #拓展Image,支持缓存
  flutter_smart_dialog: ^4.9.2 #各种弹窗 Toast/Dialog/Popup
  sticky_headers: ^0.3.0+2 #吸顶
  lottie: ^3.3.1 #lottie动画
  dynamic_color: ^1.8.1
  remixicon: ^1.4.1  
  puppeteer:
    path: packages/puppeteer


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app_config.yaml
    - assets/lotties/
